import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>zkMatching</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to zkMatching
                </h1>
                <br></br>
            
                <div className={styles.description}>Organizer and participants follow the steps below.</div>

                <div className={styles.container}> 
                    <div className={styles.step}>                          
                        <p> Step 1. Organizer creates a new Matching Event and share the generated address with participants</p>
                        <Link href="/start"> 
                            <button> Go to start page </button> 
                        </Link>
                    </div>

                    <div className={styles.step}>                         
                        <p> Step 2. Each participants commit their partner preference ranking to the blockchain</p>  
                        <Link href="/submit"> 
                            <button> Go to submit page </button> 
                        </Link>                                              
                    </div>

                    <div className={styles.step}> 
                        <p> Step 3. Organizer computes matching and register it to the blockchain</p>  
                        <Link href="/register"> 
                            <button> Go to register page </button> 
                        </Link>                                              
                    </div>

                    <div className={styles.step}> 
                        <p> Step 4. Each participants receives their result</p>  
                        <Link href="/result"> 
                            <button> Go to result page </button> 
                        </Link>                                              
                    </div>
                </div> 
            </main>

            <footer className={styles.footer}>        
            <Link href="https://github.com/ywatanabex/zku-final-project"> 
                <a>Project Repository</a> 
            </Link>
        </footer>

        </div>
    )
}
